version: 2

aliases:
  - &defaults
    working_directory: ~/core
  - &node8_executor
    docker:
      - image: circleci/node:8
  - &node9_executor
    docker:
      - image: circleci/node:9
  - &node10_executor
    docker:
      - image: circleci/node:10
  - &default_executor
    <<: *node10_executor
  - &repo_key
    repo-{{ .Branch }}-{{ .Revision }}
  - &base_config_key
    base-config-{{ .Branch }}-{{ .Revision }}
  - &restore_repo
    restore_cache:
      keys:
        - *repo_key
  - &ignore_non_dev_branches
    filters:
      tags:
        only: /.*/
      branches:
        ignore:
          - /release\/.*/
  - &execute_on_release
    filters:
      tags:
        only: /v?[0-9]+(\.[0-9]+)+([-+\.][0-9a-zA-Z]+)*/
      branches:
        ignore:
          - /.*/

jobs:
  prepare:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - checkout
      - restore_cache:
          key: *base_config_key
      - run:
          name: 'Base environment setup'
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - save_cache:
          key: *base_config_key
          paths:
            - ~/.npmrc
      - run:
          name: Install root dependencies
          command: yarn install --no-progress
      - run:
          name: Install packages dependencies and symlink them
          command: yarn bootstrap
      - save_cache:
          key: *repo_key
          paths:
            - ~/core

  # test_node8:
  #   <<: *defaults
  #   <<: *node8_executor
  #   steps:
  #     - *restore_repo
  #     - run:
  #         name: Test with Node 8
  #         command: yarn test

  # test_node9:
  #   <<: *defaults
  #   <<: *default_executor
  #   steps:
  #     - *restore_repo
  #     - run:
  #         name: Test with Node 9
  #         command: yarn test
  #     - save_cache:
  #         key: *coverage_key
  #         paths:
  #           - coverage

   test_node10:
     <<: *defaults
     <<: *node10_executor
     steps:
       - *restore_repo
       - run:
           name: Test with Node 10
           command: yarn run test

  publish_package:
    <<: *defaults
    <<: *default_executor
    steps:
      - *restore_repo
      - restore_cache:
          key: *base_config_key
      - run:
          name: Publish
          command: yarn run publish

workflows:
  version: 2
  workflow:
    jobs:
      - prepare:
          <<: *ignore_non_dev_branches
      # - test_node8:
      #     requires:
      #       - prepare
      #     <<: *ignore_non_dev_branches
      # - test_node9:
      #     requires:
      #       - prepare
      #     <<: *ignore_non_dev_branches
       - test_node10:
           requires:
             - prepare
           <<: *ignore_non_dev_branches
      - publish_package:
          requires:
            - prepare
            # - test_node8
            # - test_node9
            # - test_node10
          <<: *execute_on_release
